import { ISchemaTemplates } from '@/redux/designer/models';

const AWS_SCHEMAS: ISchemaTemplates = {
  'Security-Identity-Compliance': {
    'Directory-Service': {
      id: 'Directory-Service',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Identity-and-Access-Management': {
      id: 'Identity-and-Access-Management',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    CloudHSM: {
      id: 'CloudHSM',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Verified-Permissions': {
      id: 'Verified-Permissions',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    GuardDuty: {
      id: 'GuardDuty',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Detective: {
      id: 'Detective',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Inspector: {
      id: 'Inspector',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Cloud-Directory': {
      id: 'Cloud-Directory',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Signer: {
      id: 'Signer',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Key-Management-Service': {
      id: 'Key-Management-Service',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Firewall-Manager': {
      id: 'Firewall-Manager',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Audit-Manager': {
      id: 'Audit-Manager',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Network-Firewall': {
      id: 'Network-Firewall',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Secrets-Manager': {
      id: 'Secrets-Manager',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Macie: {
      id: 'Macie',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Cognito: {
      id: 'Cognito',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Shield: {
      id: 'Shield',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Security-Hub': {
      id: 'Security-Hub',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    WAF: {
      id: 'WAF',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Private-Certificate-Authority': {
      id: 'Private-Certificate-Authority',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Security-Lake': {
      id: 'Security-Lake',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Artifact: {
      id: 'Artifact',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Resource-Access-Manager': {
      id: 'Resource-Access-Manager',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'IAM-Identity-Center': {
      id: 'IAM-Identity-Center',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Certificate-Manager': {
      id: 'Certificate-Manager',
      category: 'Security-Identity-Compliance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  'Business-Applications': {
    Honeycode: {
      id: 'Honeycode',
      category: 'Business-Applications',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Supply-Chain': {
      id: 'Supply-Chain',
      category: 'Business-Applications',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Wickr: {
      id: 'Wickr',
      category: 'Business-Applications',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    WorkDocs: {
      id: 'WorkDocs',
      category: 'Business-Applications',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Chime-SDK': {
      id: 'Chime-SDK',
      category: 'Business-Applications',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'WorkDocs-SDK': {
      id: 'WorkDocs-SDK',
      category: 'Business-Applications',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Pinpoint: {
      id: 'Pinpoint',
      category: 'Business-Applications',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Simple-Email-Service': {
      id: 'Simple-Email-Service',
      category: 'Business-Applications',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Alexa-For-Business': {
      id: 'Alexa-For-Business',
      category: 'Business-Applications',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Chime-Voice-Connector': {
      id: 'Chime-Voice-Connector',
      category: 'Business-Applications',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Chime: {
      id: 'Chime',
      category: 'Business-Applications',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    WorkMail: {
      id: 'WorkMail',
      category: 'Business-Applications',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Pinpoint-APIs': {
      id: 'Pinpoint-APIs',
      category: 'Business-Applications',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Connect: {
      id: 'Connect',
      category: 'Business-Applications',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  Games: {
    'Open-3D-Engine': {
      id: 'Open-3D-Engine',
      category: 'Games',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Lumberyard: {
      id: 'Lumberyard',
      category: 'Games',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    GameSparks: {
      id: 'GameSparks',
      category: 'Games',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    GameLift: {
      id: 'GameLift',
      category: 'Games',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    GameKit: {
      id: 'GameKit',
      category: 'Games',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  'VR-AR': {
    Sumerian: {
      id: 'Sumerian',
      category: 'VR-AR',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  'End-User-Computing': {
    WorkLink: {
      id: 'WorkLink',
      category: 'End-User-Computing',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'WorkSpaces-Family': {
      id: 'WorkSpaces-Family',
      category: 'End-User-Computing',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    AppStream: {
      id: 'AppStream',
      category: 'End-User-Computing',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  Storage: {
    'FSx-for-WFS': {
      id: 'FSx-for-WFS',
      category: 'Storage',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Snowball-Edge': {
      id: 'Snowball-Edge',
      category: 'Storage',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'FSx-for-OpenZFS': {
      id: 'FSx-for-OpenZFS',
      category: 'Storage',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Simple-Storage-Service': {
      id: 'Simple-Storage-Service',
      category: 'Storage',
      description:
        'Amazon S3 (Simple Storage Service) provides scalable object storage (similar to Google Drive).',
      enabled: true,
      cost: {
        flat: 0,
        'per-user': 0.0046,
      },
      config: {
        versioning: {
          title: 'Versioning',
          hint: 'Enable versioning for your S3 bucket',
          type: 'boolean',
          value: false,
          required: false,
        },
        bucket_name: {
          title: 'Bucket Name',
          hint: 'Name of your component',
          type: 'string',
          value: 'bucket1',
          required: false,
        },
      },
      deploy: {
        build_directory: {
          title: 'Build Directory',
          hint: 'Location of build files in your repository',
          type: 'string',
          value: '/build',
          required: false,
        },
      },
    },
    'File-Cache': {
      id: 'File-Cache',
      category: 'Storage',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Backup: {
      id: 'Backup',
      category: 'Storage',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'FSx-for-NetApp-ONTAP': {
      id: 'FSx-for-NetApp-ONTAP',
      category: 'Storage',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Snowmobile: {
      id: 'Snowmobile',
      category: 'Storage',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Elastic-Disaster-Recovery': {
      id: 'Elastic-Disaster-Recovery',
      category: 'Storage',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Snowcone: {
      id: 'Snowcone',
      category: 'Storage',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    FSx: {
      id: 'FSx',
      category: 'Storage',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Snowball: {
      id: 'Snowball',
      category: 'Storage',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'FSx-for-Lustre': {
      id: 'FSx-for-Lustre',
      category: 'Storage',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    EFS: {
      id: 'EFS',
      category: 'Storage',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Storage-Gateway': {
      id: 'Storage-Gateway',
      category: 'Storage',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Simple-Storage-Service-Glacier': {
      id: 'Simple-Storage-Service-Glacier',
      category: 'Storage',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Elastic-Block-Store': {
      id: 'Elastic-Block-Store',
      category: 'Storage',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'S3-on-Outposts': {
      id: 'S3-on-Outposts',
      category: 'Storage',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  'Networking-Content-Delivery': {
    'Client-VPN': {
      id: 'Client-VPN',
      category: 'Networking-Content-Delivery',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Private-5G': {
      id: 'Private-5G',
      category: 'Networking-Content-Delivery',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Cloud-WAN': {
      id: 'Cloud-WAN',
      category: 'Networking-Content-Delivery',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    CloudFront: {
      id: 'CloudFront',
      category: 'Networking-Content-Delivery',
      description:
        'Amazon CloudFront is a web service for content delivery. It integrates with other Amazon Web Services to give developers and businesses an easy way to distribute content to end users with low latency, high data transfer speeds, and no commitments.',
      enabled: true,
      cost: {
        flat: 0,
        'per-user': 0.017,
      },
      config: {
        name: {
          title: 'Name',
          hint: 'Name for your CloudFront distribution',
          type: 'string',
          value: 'cloudfront',
          required: true,
        },
        bucket_name: {
          title: 'S3 Origin',
          hint: 'Origin for your CloudFront distribution',
          type: 'string',
          value: 'bucket1',
          required: true,
          hidden: true,
        },
      },
      deploy: {},
    },
    'private subnet': {
      id: 'private subnet',
      category: 'Networking-Content-Delivery',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'public subnet': {
      id: 'public subnet',
      category: 'Networking-Content-Delivery',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Route-53': {
      id: 'Route-53',
      category: 'Networking-Content-Delivery',
      description:
        'Amazon Route 53 is a scalable and highly available Domain Name System (DNS) web service.',
      enabled: true,
      cost: {
        flat: 0.5,
        'per-user': 0.0,
      },
      config: {
        domain: {
          title: 'Domain Name',
          hint: 'Domain name for your Route 53 hosted zone (excluding http:// or www)',
          type: 'string',
          value: 'stratus.com',
          required: true,
        },
      },
      deploy: {},
    },
    'Route-53 Route-Table': {
      id: 'Route-53 Route-Table',
      category: 'Networking-Content-Delivery',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Virtual-Private-Cloud': {
      id: 'Virtual-Private-Cloud',
      category: 'Networking-Content-Delivery',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Cloud-Directory': {
      id: 'Cloud-Directory',
      category: 'Networking-Content-Delivery',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'VPC-Lattice': {
      id: 'VPC-Lattice',
      category: 'Networking-Content-Delivery',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Direct-Connect': {
      id: 'Direct-Connect',
      category: 'Networking-Content-Delivery',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Verified-Access': {
      id: 'Verified-Access',
      category: 'Networking-Content-Delivery',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'App-Mesh': {
      id: 'App-Mesh',
      category: 'Networking-Content-Delivery',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Site-to-Site-VPN': {
      id: 'Site-to-Site-VPN',
      category: 'Networking-Content-Delivery',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    PrivateLink: {
      id: 'PrivateLink',
      category: 'Networking-Content-Delivery',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Cloud-Map': {
      id: 'Cloud-Map',
      category: 'Networking-Content-Delivery',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Transit-Gateway': {
      id: 'Transit-Gateway',
      category: 'Networking-Content-Delivery',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Elastic-Load-Balancing': {
      id: 'Elastic-Load-Balancing',
      category: 'Networking-Content-Delivery',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Global-Accelerator': {
      id: 'Global-Accelerator',
      category: 'Networking-Content-Delivery',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  Analytics: {
    'Kinesis-Data-Streams': {
      id: 'Kinesis-Data-Streams',
      category: 'Analytics',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Data-Pipeline': {
      id: 'Data-Pipeline',
      category: 'Analytics',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Data-Exchange': {
      id: 'Data-Exchange',
      category: 'Analytics',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Redshift: {
      id: 'Redshift',
      category: 'Analytics',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Kinesis: {
      id: 'Kinesis',
      category: 'Analytics',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Kinesis-Video-Streams': {
      id: 'Kinesis-Video-Streams',
      category: 'Analytics',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Managed-Streaming-for-Apache-Kafka': {
      id: 'Managed-Streaming-for-Apache-Kafka',
      category: 'Analytics',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Athena: {
      id: 'Athena',
      category: 'Analytics',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Glue-Elastic-Views': {
      id: 'Glue-Elastic-Views',
      category: 'Analytics',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    CloudSearch: {
      id: 'CloudSearch',
      category: 'Analytics',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Kinesis-Data-Analytics': {
      id: 'Kinesis-Data-Analytics',
      category: 'Analytics',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Lake-Formation': {
      id: 'Lake-Formation',
      category: 'Analytics',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    QuickSight: {
      id: 'QuickSight',
      category: 'Analytics',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Kinesis-Firehose': {
      id: 'Kinesis-Firehose',
      category: 'Analytics',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    DataZone: {
      id: 'DataZone',
      category: 'Analytics',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Clean-Rooms': {
      id: 'Clean-Rooms',
      category: 'Analytics',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Glue: {
      id: 'Glue',
      category: 'Analytics',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'OpenSearch-Service': {
      id: 'OpenSearch-Service',
      category: 'Analytics',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    EMR: {
      id: 'EMR',
      category: 'Analytics',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Glue-DataBrew': {
      id: 'Glue-DataBrew',
      category: 'Analytics',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    FinSpace: {
      id: 'FinSpace',
      category: 'Analytics',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  Database: {
    'RDS-on-VMware': {
      id: 'RDS-on-VMware',
      category: 'Database',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Keyspaces: {
      id: 'Keyspaces',
      category: 'Database',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'MemoryDB-for-Redis': {
      id: 'MemoryDB-for-Redis',
      category: 'Database',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Timestream: {
      id: 'Timestream',
      category: 'Database',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Neptune: {
      id: 'Neptune',
      category: 'Database',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    RDS: {
      id: 'RDS',
      category: 'Database',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    DynamoDB: {
      id: 'DynamoDB',
      category: 'Database',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    DocumentDB: {
      id: 'DocumentDB',
      category: 'Database',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Aurora: {
      id: 'Aurora',
      category: 'Database',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    ElastiCache: {
      id: 'ElastiCache',
      category: 'Database',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Database-Migration-Service': {
      id: 'Database-Migration-Service',
      category: 'Database',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  'Developer-Tools': {
    CodeCommit: {
      id: 'CodeCommit',
      category: 'Developer-Tools',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Cloud-Development-Kit': {
      id: 'Cloud-Development-Kit',
      category: 'Developer-Tools',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Application-Composer': {
      id: 'Application-Composer',
      category: 'Developer-Tools',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Corretto: {
      id: 'Corretto',
      category: 'Developer-Tools',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    CodeArtifact: {
      id: 'CodeArtifact',
      category: 'Developer-Tools',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Command-Line-Interface': {
      id: 'Command-Line-Interface',
      category: 'Developer-Tools',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Cloud-Control-API': {
      id: 'Cloud-Control-API',
      category: 'Developer-Tools',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    CodeDeploy: {
      id: 'CodeDeploy',
      category: 'Developer-Tools',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'X-Ray': {
      id: 'X-Ray',
      category: 'Developer-Tools',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    CodePipeline: {
      id: 'CodePipeline',
      category: 'Developer-Tools',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    CodeStar: {
      id: 'CodeStar',
      category: 'Developer-Tools',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    CodeCatalyst: {
      id: 'CodeCatalyst',
      category: 'Developer-Tools',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    CodeBuild: {
      id: 'CodeBuild',
      category: 'Developer-Tools',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Cloud9: {
      id: 'Cloud9',
      category: 'Developer-Tools',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Tools-and-SDKs': {
      id: 'Tools-and-SDKs',
      category: 'Developer-Tools',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    CloudShell: {
      id: 'CloudShell',
      category: 'Developer-Tools',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  'Internet-of-Things': {
    'IoT-ExpressLink': {
      id: 'IoT-ExpressLink',
      category: 'Internet-of-Things',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'IoT-TwinMaker': {
      id: 'IoT-TwinMaker',
      category: 'Internet-of-Things',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'IoT-Analytics': {
      id: 'IoT-Analytics',
      category: 'Internet-of-Things',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'IoT-Core': {
      id: 'IoT-Core',
      category: 'Internet-of-Things',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'IoT-Device-Management': {
      id: 'IoT-Device-Management',
      category: 'Internet-of-Things',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'IoT-FleetWise': {
      id: 'IoT-FleetWise',
      category: 'Internet-of-Things',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'IoT-Device-Defender': {
      id: 'IoT-Device-Defender',
      category: 'Internet-of-Things',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'IoT-Greengrass': {
      id: 'IoT-Greengrass',
      category: 'Internet-of-Things',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'IoT-EduKit': {
      id: 'IoT-EduKit',
      category: 'Internet-of-Things',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'IoT-RoboRunner': {
      id: 'IoT-RoboRunner',
      category: 'Internet-of-Things',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'IoT-Events': {
      id: 'IoT-Events',
      category: 'Internet-of-Things',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'IoT-1-Click': {
      id: 'IoT-1-Click',
      category: 'Internet-of-Things',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    FreeRTOS: {
      id: 'FreeRTOS',
      category: 'Internet-of-Things',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'IoT-Button': {
      id: 'IoT-Button',
      category: 'Internet-of-Things',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'IoT-Things-Graph': {
      id: 'IoT-Things-Graph',
      category: 'Internet-of-Things',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'IoT-SiteWise': {
      id: 'IoT-SiteWise',
      category: 'Internet-of-Things',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  Containers: {
    'ECS-Anywhere': {
      id: 'ECS-Anywhere',
      category: 'Containers',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Red-Hat-OpenShift-Service-on-AWS': {
      id: 'Red-Hat-OpenShift-Service-on-AWS',
      category: 'Containers',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Elastic-Container-Service': {
      id: 'Elastic-Container-Service',
      category: 'Containers',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'EKS-Cloud': {
      id: 'EKS-Cloud',
      category: 'Containers',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Elastic-Kubernetes-Service': {
      id: 'Elastic-Kubernetes-Service',
      category: 'Containers',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'EKS-Distro': {
      id: 'EKS-Distro',
      category: 'Containers',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Elastic-Container-Registry': {
      id: 'Elastic-Container-Registry',
      category: 'Containers',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Fargate: {
      id: 'Fargate',
      category: 'Containers',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'EKS-Anywhere': {
      id: 'EKS-Anywhere',
      category: 'Containers',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  Robotics: {
    RoboMaker: {
      id: 'RoboMaker',
      category: 'Robotics',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  Compute: {
    'Thinkbox-Deadline': {
      id: 'Thinkbox-Deadline',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Elastic-Fabric-Adapter': {
      id: 'Elastic-Fabric-Adapter',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'NICE-DCV': {
      id: 'NICE-DCV',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Batch: {
      id: 'Batch',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'EC2-Image-Builder': {
      id: 'EC2-Image-Builder',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'EC2-Spot-Instance': {
      id: 'EC2-Spot-Instance',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Local-Zones': {
      id: 'Local-Zones',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'App-Runner': {
      id: 'App-Runner',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Outposts-rack': {
      id: 'Outposts-rack',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    ParallelCluster: {
      id: 'ParallelCluster',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Outposts-family': {
      id: 'Outposts-family',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Nitro-Enclaves': {
      id: 'Nitro-Enclaves',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Outposts-servers': {
      id: 'Outposts-servers',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Thinkbox-Frost': {
      id: 'Thinkbox-Frost',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Thinkbox-Krakatoa': {
      id: 'Thinkbox-Krakatoa',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Compute-Optimizer': {
      id: 'Compute-Optimizer',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Lambda: {
      id: 'Lambda',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'NICE-EnginFrame': {
      id: 'NICE-EnginFrame',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'EC2-Auto-Scaling': {
      id: 'EC2-Auto-Scaling',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Thinkbox-Stoke': {
      id: 'Thinkbox-Stoke',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Wavelength: {
      id: 'Wavelength',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Thinkbox-XMesh': {
      id: 'Thinkbox-XMesh',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'VMware-Cloud-on-AWS': {
      id: 'VMware-Cloud-on-AWS',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Bottlerocket: {
      id: 'Bottlerocket',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Thinkbox-Sequoia': {
      id: 'Thinkbox-Sequoia',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Genomics-CLI': {
      id: 'Genomics-CLI',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'SimSpace-Weaver': {
      id: 'SimSpace-Weaver',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Lightsail: {
      id: 'Lightsail',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    EC2: {
      id: 'EC2',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Fargate: {
      id: 'Fargate',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Elastic-Beanstalk': {
      id: 'Elastic-Beanstalk',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Serverless-Application-Repository': {
      id: 'Serverless-Application-Repository',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Application-Auto-Scaling': {
      id: 'Application-Auto-Scaling',
      category: 'Compute',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  'Cloud-Financial-Management': {
    Budgets: {
      id: 'Budgets',
      category: 'Cloud-Financial-Management',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Billing-Conductor': {
      id: 'Billing-Conductor',
      category: 'Cloud-Financial-Management',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Cost-Explorer': {
      id: 'Cost-Explorer',
      category: 'Cloud-Financial-Management',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Reserved-Instance-Reporting': {
      id: 'Reserved-Instance-Reporting',
      category: 'Cloud-Financial-Management',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Savings-Plans': {
      id: 'Savings-Plans',
      category: 'Cloud-Financial-Management',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Application-Cost-Profiler': {
      id: 'Application-Cost-Profiler',
      category: 'Cloud-Financial-Management',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Cost-and-Usage-Report': {
      id: 'Cost-and-Usage-Report',
      category: 'Cloud-Financial-Management',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  Satellite: {
    'Ground-Station': {
      id: 'Ground-Station',
      category: 'Satellite',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  Blockchain: {
    'Quantum-Ledger-Database': {
      id: 'Quantum-Ledger-Database',
      category: 'Blockchain',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Managed-Blockchain': {
      id: 'Managed-Blockchain',
      category: 'Blockchain',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  'Management-Governance': {
    'Personal-Health-Dashboard': {
      id: 'Personal-Health-Dashboard',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Resilience-Hub': {
      id: 'Resilience-Hub',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    CloudWatch: {
      id: 'CloudWatch',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Resource-Explorer': {
      id: 'Resource-Explorer',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Proton: {
      id: 'Proton',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Well-Architected-Tool': {
      id: 'Well-Architected-Tool',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    AppConfig: {
      id: 'AppConfig',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'License-Manager': {
      id: 'License-Manager',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Systems-Manager': {
      id: 'Systems-Manager',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Fault-Injection-Simulator': {
      id: 'Fault-Injection-Simulator',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Managed-Grafana': {
      id: 'Managed-Grafana',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    CloudFormation: {
      id: 'CloudFormation',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Config: {
      id: 'Config',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Organizations: {
      id: 'Organizations',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Managed-Service-for-Prometheus': {
      id: 'Managed-Service-for-Prometheus',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Launch-Wizard': {
      id: 'Launch-Wizard',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Service-Management-Connector': {
      id: 'Service-Management-Connector',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    CloudTrail: {
      id: 'CloudTrail',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Service-Catalog': {
      id: 'Service-Catalog',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    OpsWorks: {
      id: 'OpsWorks',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Chatbot: {
      id: 'Chatbot',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Distro-for-OpenTelemetry': {
      id: 'Distro-for-OpenTelemetry',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Backint-Agent': {
      id: 'Backint-Agent',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Trusted-Advisor': {
      id: 'Trusted-Advisor',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Management-Console': {
      id: 'Management-Console',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Control-Tower': {
      id: 'Control-Tower',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Auto-Scaling': {
      id: 'Auto-Scaling',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Application-Auto-Scaling': {
      id: 'Application-Auto-Scaling',
      category: 'Management-Governance',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  'Media-Services': {
    'Elemental-MediaConnect': {
      id: 'Elemental-MediaConnect',
      category: 'Media-Services',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Elemental-MediaStore': {
      id: 'Elemental-MediaStore',
      category: 'Media-Services',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Elemental-Link': {
      id: 'Elemental-Link',
      category: 'Media-Services',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Elemental-Live': {
      id: 'Elemental-Live',
      category: 'Media-Services',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Elemental-MediaConvert': {
      id: 'Elemental-MediaConvert',
      category: 'Media-Services',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Elemental-Conductor': {
      id: 'Elemental-Conductor',
      category: 'Media-Services',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Elemental-MediaPackage': {
      id: 'Elemental-MediaPackage',
      category: 'Media-Services',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Kinesis-Video-Streams': {
      id: 'Kinesis-Video-Streams',
      category: 'Media-Services',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Elemental-MediaTailor': {
      id: 'Elemental-MediaTailor',
      category: 'Media-Services',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Elastic-Transcoder': {
      id: 'Elastic-Transcoder',
      category: 'Media-Services',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Nimble-Studio': {
      id: 'Nimble-Studio',
      category: 'Media-Services',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Elemental-Server': {
      id: 'Elemental-Server',
      category: 'Media-Services',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Elemental-Appliances-&-Software': {
      id: 'Elemental-Appliances-&-Software',
      category: 'Media-Services',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Elemental-MediaLive': {
      id: 'Elemental-MediaLive',
      category: 'Media-Services',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Interactive-Video-Service': {
      id: 'Interactive-Video-Service',
      category: 'Media-Services',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Elemental-Delta': {
      id: 'Elemental-Delta',
      category: 'Media-Services',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  'Machine-Learning': {
    Neuron: {
      id: 'Neuron',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Polly: {
      id: 'Polly',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Personalize: {
      id: 'Personalize',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Elastic-Inference': {
      id: 'Elastic-Inference',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    CodeWhisperer: {
      id: 'CodeWhisperer',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Rekognition: {
      id: 'Rekognition',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Monitron: {
      id: 'Monitron',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Lookout-for-Equipment': {
      id: 'Lookout-for-Equipment',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Panorama: {
      id: 'Panorama',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Transcribe: {
      id: 'Transcribe',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'SageMaker-Studio-Lab': {
      id: 'SageMaker-Studio-Lab',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    CodeGuru: {
      id: 'CodeGuru',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Lex: {
      id: 'Lex',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Translate: {
      id: 'Translate',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Forecast: {
      id: 'Forecast',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Textract: {
      id: 'Textract',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'SageMaker-Ground-Truth': {
      id: 'SageMaker-Ground-Truth',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Apache-MXNet-on-AWS': {
      id: 'Apache-MXNet-on-AWS',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Augmented-AI-A2I': {
      id: 'Augmented-AI-A2I',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    DeepRacer: {
      id: 'DeepRacer',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Comprehend-Medical': {
      id: 'Comprehend-Medical',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    SageMaker: {
      id: 'SageMaker',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Lookout-for-Vision': {
      id: 'Lookout-for-Vision',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'TensorFlow-on-AWS': {
      id: 'TensorFlow-on-AWS',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Deep-Learning-Containers': {
      id: 'Deep-Learning-Containers',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Lookout-for-Metrics': {
      id: 'Lookout-for-Metrics',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    HealthLake: {
      id: 'HealthLake',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Deep-Learning-AMIs': {
      id: 'Deep-Learning-AMIs',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Fraud-Detector': {
      id: 'Fraud-Detector',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Kendra: {
      id: 'Kendra',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Omics: {
      id: 'Omics',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    TorchServe: {
      id: 'TorchServe',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    DeepComposer: {
      id: 'DeepComposer',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    DeepLens: {
      id: 'DeepLens',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'DevOps-Guru': {
      id: 'DevOps-Guru',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Comprehend: {
      id: 'Comprehend',
      category: 'Machine-Learning',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  'Quantum-Technologies': {
    Braket: {
      id: 'Braket',
      category: 'Quantum-Technologies',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  'Migration-Transfer': {
    'Application-Discovery-Service': {
      id: 'Application-Discovery-Service',
      category: 'Migration-Transfer',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Server-Migration-Service': {
      id: 'Server-Migration-Service',
      category: 'Migration-Transfer',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Migration-Evaluator': {
      id: 'Migration-Evaluator',
      category: 'Migration-Transfer',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Transfer-Family': {
      id: 'Transfer-Family',
      category: 'Migration-Transfer',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Application-Migration-Service': {
      id: 'Application-Migration-Service',
      category: 'Migration-Transfer',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Migration-Hub': {
      id: 'Migration-Hub',
      category: 'Migration-Transfer',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    DataSync: {
      id: 'DataSync',
      category: 'Migration-Transfer',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Mainframe-Modernization': {
      id: 'Mainframe-Modernization',
      category: 'Migration-Transfer',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  'Application-Integration': {
    AppFlow: {
      id: 'AppFlow',
      category: 'Application-Integration',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    MQ: {
      id: 'MQ',
      category: 'Application-Integration',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Console-Mobile-Application': {
      id: 'Console-Mobile-Application',
      category: 'Application-Integration',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Managed-Workflows-for-Apache-Airflow': {
      id: 'Managed-Workflows-for-Apache-Airflow',
      category: 'Application-Integration',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'API-Gateway': {
      id: 'API-Gateway',
      category: 'Application-Integration',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    AppSync: {
      id: 'AppSync',
      category: 'Application-Integration',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Step-Functions': {
      id: 'Step-Functions',
      category: 'Application-Integration',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Simple-Queue-Service': {
      id: 'Simple-Queue-Service',
      category: 'Application-Integration',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Simple-Notification-Service': {
      id: 'Simple-Notification-Service',
      category: 'Application-Integration',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    EventBridge: {
      id: 'EventBridge',
      category: 'Application-Integration',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Express-Workflows': {
      id: 'Express-Workflows',
      category: 'Application-Integration',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  'Front-End-Web-Mobile': {
    'Device-Farm': {
      id: 'Device-Farm',
      category: 'Front-End-Web-Mobile',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Amplify: {
      id: 'Amplify',
      category: 'Front-End-Web-Mobile',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Location-Service': {
      id: 'Location-Service',
      category: 'Front-End-Web-Mobile',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
  'Customer-Enablement': {
    'Training-Certification': {
      id: 'Training-Certification',
      category: 'Customer-Enablement',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Managed-Services': {
      id: 'Managed-Services',
      category: 'Customer-Enablement',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Support: {
      id: 'Support',
      category: 'Customer-Enablement',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    IQ: {
      id: 'IQ',
      category: 'Customer-Enablement',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    'Professional-Services': {
      id: 'Professional-Services',
      category: 'Customer-Enablement',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    rePost: {
      id: 'rePost',
      category: 'Customer-Enablement',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
    Activate: {
      id: 'Activate',
      category: 'Customer-Enablement',
      description: '',
      enabled: true,
      cost: {},
      config: {},
      deploy: {},
    },
  },
};

export default AWS_SCHEMAS;
